[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

MONGODB_URI=mongodb+srv://lambattannabil2000_db_user:Nabil2000@cluster0.dnslv2d.mongodb.net/?appName=Cluster0
JWT_SECRET=c46807cdbe18c959595905be5f750b926e34dd211f6444ef9f74db3c2739d407
NEXT_PUBLIC_API_URL=http://localhost:3000
CLOUDINARY_API_KEY=645823478987726
CLOUDINARY_API_SECRET=_LzFjY3k16MKXLHGLtXYnKfxow0
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dqyjujuym
NEXT_PUBLIC_CLOUDINARY_PRESET_PRODUCTS=fithub_products
NEXT_PUBLIC_SITE_URL=https://fithub-gym-ecom.netlify.app
